In [1]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

17

In [5]:
#now we need sequence from these

sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [6]:
# different size sequences so we add padding
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [7]:
import tensorflow
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [14]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [25]:
model = Sequential()
model.add(Embedding(18, output_dim=2, input_length=5))

model.build(input_shape=(None,2))
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 2, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile('adam', 'accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
[[[ 0.04296209 -0.04593892]
  [ 0.0488185   0.04699229]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]]

 [[ 0.0488185   0.04699229]
  [ 0.0488185   0.04699229]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]]

 [[-0.01985499  0.04499311]
  [-0.01985499  0.04499311]
  [-0.00419402 -0.03167721]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]]

 [[ 0.02708085  0.00550931]
  [ 0.04517183 -0.01484468]
  [ 0.02708085  0.00550931]
  [ 0.0488185   0.04699229]
  [ 0.02708085  0.00550931]]

 [[ 0.02363786 -0.04617388]
  [-0.04320839  0.04695072]
  [ 0.01341018 -0.02656239]
  [-0.04907273 -0.00617903]
  [-0.00700804 -0.01559868]]

 [[ 0.0055529   0.03501355]
  [ 0.0055529   0.03501355]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.01559868]]

 [[-0.04603102 -0.01205063]
  [-0.04603102 -0.01205063]
  [-0.00700804 -0.01559868]
  [-0.00700804 -0.0155986

: 

In [9]:
from keras.datasets import imdb
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [10]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [11]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [12]:
X_train.shape

(25000, 50)

In [23]:
model = Sequential()
model.add(Embedding(200000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.build(input_shape=(None, 50))

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 50, 2)          │       400,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401,153 (1.53 MB)

 Trainable params: 401,153 (1.53 MB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - acc: 0.5864 - loss: 0.6511 - val_acc: 0.7803 - val_loss: 0.4808
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 30ms/step - acc: 0.8232 - loss: 0.3981 - val_acc: 0.8097 - val_loss: 0.4311
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 22ms/step - acc: 0.8948 - loss: 0.2693 - val_acc: 0.7850 - val_loss: 0.4644
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 22ms/step - acc: 0.9297 - loss: 0.1937 - val_acc: 0.7986 - val_loss: 0.4817
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 31ms/step - acc: 0.9492 - loss: 0.1466 - val_acc: 0.7933 - val_loss: 0.5780
